### PR TITLE
Add supervisord attributes

### PR DESCRIPTION
**Pull request by dcrosta**
This adds a bunch of attributes I find handy to the `supervisord_program` LWRP. Hope you find it useful.

### CODE REVIEW

**Comment by mpasternacki** [comment]
Thanks! Merged and uploaded to community.opscode.com.

**Comment by dcrosta** [comment]
Hm... don't see the new version at http://community.opscode.com/cookbooks/supervisord

**Comment by mpasternacki** [comment]
Right, pushed again. Works now.

**Comment by dcrosta** [comment]
Thanks!

**Pull request merged**
